# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170610_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': '新闻表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='favor',
            field=models.ManyToManyField(null=True, to='repository.News'),
        ),
    ]
