# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170610_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='favor_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='favor',
            field=models.ManyToManyField(to='repository.News'),
        ),
    ]
